export { default as AlphadevIcon } from './AlphadevIcon.png'
export { default as AlphadevLogo } from './AlphadevLogo.png'
export { default as BgLogin } from './BgLogin.webp'
export { default as BannerImage } from './BannerImage.webp'
export { default as NoData } from './NoData.webp'
export { default as NoNotification } from './NoNotification.webp'
