import type { Metadata } from "next";
import { DefaultLayout } from "@/component/layout";
import "@/style/globals.css";

export const metadata: Metadata = {
  title: "Edge Dash",
  description: "Generated by create next app",
};

export interface AppLayoutProps {
  children: React.ReactNode;
}

export default function AppLayout({ children }: AppLayoutProps) {
  return (
    <html lang="en">
      <body className="font-poppins h-screen bg-gray-100 text-sm text-gray-600 antialiased dark:bg-gray-900 dark:text-gray-200">
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
